development:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
test: &TEST  
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
production:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
cucumber:
  <<: *TEST
